dist: trusty
sudo: false
language: go
go:
  - "1.11"
env:
  global:
    - GO111MODULE=on
    - PATH=$PATH:$GOPATH/bin
    - GOLANGCILINT=v1.10.2
install:
  - go build
before_script:
  - GO111MODULE=auto go get github.com/mgechev/revive
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - revive
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload.'
